#include <iostream>
using namespace std;
int main() {
	setlocale(0, "");
	int age = 20;
	cout << "age = " << age << " Тип:int"<< endl;
	int Number_First = 10;
	cout << "number = " << Number_First << " Тип:int"<< endl;
	int members = 27;
	cout << "members = " << members << " Тип:int" << endl;
	int pixel = 1080;
	cout << "pixel = " << pixel << " Тип:int" << endl;
	int health = 100;
	cout << "health = " << health << " Тип:int" << endl;
	short month = 12;
	cout << "month = " << month << " Тип:short" << endl;
	short day = 31;
	cout << "day = " << day << " Тип:short" << endl;
	short minutes = 60;
	cout << "minutes = " << minutes << " Тип:short" << endl;
	short seconds = 30;
	cout << "seconds = " << seconds << " Тип:short" << endl;
	short floor = 7;
	cout << "floor = " << floor << " Тип:short" << endl;
	float weight = 68.5;
	cout << "weight = " << weight << " Тип:float" << endl;
	float time = 2.5;
	cout << "time = " << time << " Тип:float" << endl;
	float size = 12.6;
	cout << "size = " << size << " Тип:float" << endl;
	float speed = 110.5;
	cout << "speed = " << speed << " Тип:float" << endl;
	float procent = 15.8;
	cout << "procent = " << procent << " Тип:float" << endl;
	double cash = 50000.12;
	cout << "cash = " << cash << " Тип:double"<< endl;
	double price = 12341.23;
	cout << "price = " << price << " Тип:double" << endl;
	double gravity = 9.806;
	cout << "gravity = " << gravity << " Тип:double" << endl;
	double pi = 3.1415;
	cout << "pi = " << pi << " Тип:double" << endl;
	double course = 312.21;
	cout << "course = " << course << " Тип:double" << endl;
	bool ages = 1;
	cout << "age = " << ages << " Тип: bool" << endl;
	bool Mouth_Open = 0;
	cout << "Mouth = " << Mouth_Open << " Тип: bool" << endl;
	bool Window_Open = 1;
	cout << "Window = " << Window_Open << " Тип: bool" << endl;
	bool Computer_On = 1;
	cout << "Computer = " << Computer_On << " Тип: bool" << endl;
	bool Long_Hand = 0;
	cout << "Long_Hand = " << Long_Hand << " Тип: bool" << endl;
	char sign = '+';
	cout << "sign = " << sign << " Тип:char" << endl;
	char letter = 'A';
	cout << "letter = " << letter << " Тип:char" << endl;
	char oper_ator = '*';
	cout << "operator = " << oper_ator << " Тип:char" << endl;
	char currency = '$';
	cout << "Currency = " << currency << " Тип:char" << endl;
	char number = '2';
	cout << "number = " << number << " Тип:char" << endl;
	string name = "Сергей";
	cout << "name = " << name << " Тип:string" << endl;
	string surname = "Остопов";
	cout << "surname = " << surname << " Тип:string" << endl;
	string city = "Moscow";
	cout << "City = " << city << " Тип:string" << endl;
	string country = "Russia";
	cout << "Counrty = " << country << " Тип:string" << endl;
	string job = "Программист";
	cout << "Job = " << job << " Тип:string" << endl;
	return 0;
}

